Input:
    input_fastq_dir: "/project/thrash_89/db/EAGER_metaG_for_ck/interleaved_metaG/qual_trim_after_interleaving/brett_cat"
    input_fastq_suffix: "_all.fastq"
    input_fastq_csv_file: ""
output_dir: "/project/thrash_89/db/EAGER_metaG_for_ck/pipeline_assemblies"  
slurm_scheduling:
    uses_slurm_scheduling: "True"
    slurm_resource_paramter_yml: ""
